# Generated by Django 4.2.6 on 2023-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ip', models.GenericIPAddressField()),
                ('previous_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
