# Generated by Django 4.2.6 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IIP', '0002_server_delete_ipaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
